# .bash_profile is executed for
# login shells, while .bashrc is executed for interactive
# non-login shells.
# This file is executed with you log in or start a shell with the -l option.
# Mac OS X Terminal starts its windows with the -l option.

test -f ~/.bashrc && source ~/.bashrc

# only use rvm when we need it.  touch ~/use_rvm and restart terminal
[[ -e "$HOME/use_rvm" ]] && [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
