# .bashrc
# Modification History
# ~~~~~~~~~~~~~~~~~~~~
# Jan-15 glt    Comment out Oracle and Android dev setups until we want to use them again
#
# Nov-14 glt    Change "exit" to "return" in interactivity test
#               because exiting was causing X11/XQuartz to fail to start.
# Mar-14 glt    Moved PATH changing code form .bashrc_aliases
#               Removed chroot_debian code and added git branch to prompt
#		Add defines to support Emacs as a Daemon
# Nov-13 glt	Added PKG_CONFIG_PATH
# Jul-09 glt	Added code from my personal bash preference file

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig

export ALTERNATE_EDITOR=""
# export EDITOR=emacsclient
export EDITOR=gvim

# don't put duplicate lines in the history and do not save commands
# that begin with space. See bash(1) for more options
# export HISTCONTROL=ignoreboth

# -s[et] shell options
#  notify:    print bg job notifications immediately
#  ignoreeof: Require at least 10 EOFs before terminating a shell
set -o notify
set -o ignoreeof

#  histappend: append to history file, do not overwrite
#  checkwinsize: check window size after every command, updating LINES & COLUMNS if needed.
shopt -s histappend checkwinsize

# set default file protection to 750
umask 027

#++
# Prompt Setting code
#
# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
  xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
  if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    color_prompt=yes
  else
    color_prompt=
  fi
fi

# function for PS1 to display [ git branch] when it is defined
function __show_git_branch() {
  branch=`git rev-parse --abbrev-ref HEAD 2>/dev/null`
  [ -n "$branch" ] && echo " [$branch]"
}

# Most interesting prompt escapes:
#    \h - hostname up until first '.'  (\H for entire)
#    \j - # jobs managed by shell
#    \u - username,
#    \w - cwd, \W - cwd basename
#    \! - cmd history number
#PS1='-- \u@\h:\w$(__show_git_branch) --\n\!\$ '
PS1='$(tput setaf 7)-- \u@\h:\w$(__show_git_branch) --$(tput sgr0)\n\!\$ '

# add indicator to prompt for invocation depth
case $SHLVL in
  1) PS1="${PS1}";;
  2) PS1="${PS1}> " ;;
  *) PS1="${PS1}>> " ;;
esac

#
#-- end Prompt setting code

# add paths for Linux brew
case $(uname) in
  Linux)
    export PATH="$HOME/.linuxbrew/bin:$PATH"
    export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
    export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
    ;;
esac

#++
# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

# add directories to PATH if they are not there already
# Move /usr/local/bin to front, if it is already there.  Add it to the front, if not.
case $PATH in
  */usr/local/bin*)   # path is present remove it and add to beginning
    PATH=`echo "$PATH" | sed 's=/usr/local/bin[:]*==;s=^=/usr/local/bin:='`
    ;;
  *)	                # add it to the start
    PATH="/usr/local/bin:$PATH"
    ;;
esac
case $PATH in
  *~/bin*)   		      # already there
    ;;
  *)                  # append it
    PATH="~/bin:$PATH"
    ;;
esac
case $PATH in
  */usr/sbin*)		    # already there
    ;;
  *)                  # append it
    PATH="$PATH"":/usr/sbin" ;;
esac
#case $PATH in
#  */usr/bin/mh*)     # already there
#    ;;
#  *)                 # append it
#    PATH="$PATH"":/usr/bin/mh" 
#    ;;
#esac

# gt 2013: Enable shims and autocomplete for Ruby and completion for Brew
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
source `brew --repository`/Library/Contributions/brew_bash_completion.sh
export PATH

#
#--


### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Added for homebrew
export PATH=/usr/local/sbin:$PATH

# Added for Android OS building (/opt/local/bin must appear before /usr/bin)
export PATH=/opt/local/bin:$PATH

# inhibit Oracle client use, since no longer at Merge
if false; then
  ### Added to support Oracle client (Merge, Sep 2014)
  export DYLD_LIBRARY_PATH="$HOME/.oracle/instantclient_11_2"
  export NLS_LANG="AMERICAN_AMERICA.UTF8"
  export TNS_ADMIN="$HOME/.oracle/instantclient_11_2/admin"
  export PATH="$DYLD_LIBRARY_PATH:$PATH"

  # Ansible (Added for Merge)
  export ANSIBLE_HOSTS=~/.ansible_hosts
fi

# inhibit enabling Android environment, for now
if false
then
  case ${uname} in
    Darwin)
      adt_home=/Volumes/XtraData/Users/tarsa/opt/adt-bundle
      export PATH=${PATH}:${adt_home}/sdk/platform-tools:${adt_home}/sdk/tools
      ;;
  esac
  # ccache (for Android compilations)
  export USE_CCACHE=1
  # mount the android file image
  function mountAndroid { hdiutil attach ~/xsrc/disk-android.dmg.sparseimage -mountpoint /Volumes/android; }
  mountAndroid
fi

# raise the limit on the number of open file descriptors to support parallel builds.
# ulimit -S -n 1024

# Added for Time2Track
case ${uname} in
  Darwin)
    export FORMSTACK_TOKEN='e3289978afc2f05955bb9d70736fd77f'
    ;;
esac

