# .bash_aliases
# Modification History
# ~~~~~~~~~~~~~~~~~~~~
# Aug-14 glt  Remove ancient 'print' and other older, unused aliases.
# Jul-14 glt  Add alias for pry-rescue with spinach.  [May not be working]
# Mar-14 glt	Add alias for common Heroku mispelling
#		Change emacs aliases to use Emacs daemon
# Jan-14 glt	Add alias for git to hub; added completion for hub and git
# 	 	Add alias for calling MacOSX Emacs directly from cmd line
# 	 	Add some git aliases
# Dec-13 glt	Adjust emacs definitions for MacOSX
# Nov-13 glt	Add code to enable shims and autocompl for RUBY and 
# 	 	completion for homebrew; removed mh directory append
# Dec-11 glt	Add hptemp alias
# Apr-11 glt	Change $* to "$@" so that multi-word args work properly.
# Jan-10 glt	add check for /usr/bin/mh in PATH
# Aug-09 glt	add local dirs to PATH, if needed
# Jul-09 glt	convert to .bash_aliases for Ubuntu
# Mar-01 glt	Add aliases for NetApp
# Jun-00 GLT	Update DISPLAY setting for combined Tru64/Linux use
#		force TERM=xterm-* to be TERM=xterm for Tru64
# Dec-98 GLT	Replace most \!* csh aliases with echo_and_do invocation
#		Comment out those that did not translate well
# Nov-98 GLT	Port from .cshrc

#
# allows args to be displayed prior to execution
# arg1 must be the command name
#
function echo_and_do()
    {
    echo 2>&1 "--> $@" 2> /dev/tty
    "$@"
    }

#
# allows cmd to immediately execute in the background
# arg 1 must be the command name
#
function do_background()
    {
    "$@" &
    }

#
# executes arg1 as a command after executing the remainder
# of the line as a command
# arg 1 must be the post-command in its entirety
# arg 2 must be the command name
#
function do_after()
    {
    local postcmd=$1
    shift

    "$@" ; $postcmd
    }


#++
# add completion extensions

source ~/.git-completion.bash
source ~/.hub.bash_completion.sh

# if ls supports --color, use it
if ls --color /tmp > /dev/null 2>&1
then
  alias ls='ls -FshH --color'
else
  alias ls='ls -FshH'
fi

# .ackrc file may be a better place for this kind of thing
alias   ack='ack --ignore-file=ext:log,svg,txt --ignore-dir={tmp,bower_components,node_modules}'
alias ackns='ack --ignore-file=ext:log,svg,txt --ignore-dir={tmp,bower_components,node_modules,spec,features}'

#alias ffm='defaults write com.apple.Terminal FocusFollowsMouse -bool '
alias cd='pushd'
alias be='bundle exec'
alias bk='popd'
# gt jan14 alias cp='echo_and_do /bin/cp'
alias cp="cp -v"
alias cleanup#='find ~ -name "#*" -exec rm -rf {} \; &'
alias cls=clear
alias du='du -h' # human-readable sizes
alias df='df -Ph' # human-readable sizes
alias ecco32="wine '/Users/tarsa/.wine/drive_c/Program Files/ECCO/ecco32' 2> /tmp/ecco.wine.errs.txt &"
alias ecco="wine '/Users/tarsa/.wine/drive_c/Program Files/ECCO/eccoext' 2> /tmp/ecco.wine.errs.txt &"
alias findall="grep -ris"
# alias xemacs='do_background emacs'
alias xemacs='do_background ~/bin/ec --quiet'
# on Mac OS X, we prefer to use Emacs in the terminal window
alias emacs='\ec -nw --quiet'
#alias ftp="\ftp -i"
alias gd="git diff"
case `uname` in
  Linux)
    ;;
  "*")
    alias git=hub
    ;;
esac
alias grep='grep -s'  # inhibit "...Is a directory" messages
alias gs="git status"
alias gvim='gvim 2> /dev/null 1>&2'
alias herokup=heroku
alias his='x;history 22'
alias hist='x;history 44 | pr -w80 -2 -l22 -t'
alias hptemp='sudo hpasmcli -s "show temp"'
alias iostat='iostat -h' # human-readable sizes
alias load=uptime
function lookup () {
  google-chrome http://www.google.com/search?q=“$1″
}
alias mail=Mail
alias mar='sed "s/^/	/" '
# MH aliases
	alias n="next"
	alias rs="rmm;next"
	alias rp="rmm;prev"
	alias pack="folder -pack"
	alias pick="do_after 'scan pick' pick -sequence pick"
	alias repl="repl -filter ~/MH-mail/repl.filter -nocc all"
#glt98 	alias unrmm="mv ~/MH-mail/inbox/[#,]\!^ ~/MH-mail/inbox/\!^"
	alias mpc='set _p=`mhpath cur`; pc-conv $_p > /tmp/tmp$$ && rmm cur && mv /tmp/tmp$$ $_p && show cur'
	alias cur="folder | sed 's/+//g;s/\.//g;s/;//g' | awk '{printf "'"+%s %s\n", $1, $9}'"'"  
	alias jforw="forw -form joke-components"
alias mq='/usr/lib/sendmail -bp'
alias mqueue=mq
alias mv='echo_and_do /bin/mv'
alias pc-conv='sed -f ~/bin/PC-conv.sed'
alias pkgupdate="do_background gksudo synaptic"
alias pl='sed -f $HOME/bin/plist.sed $HOME/phone.lst | grep -i '
alias rcp="echo_and_do /bin/rcp"
alias reload='xrdb -load ~/.Xdefaults'
# spin alias may not work.
alias spin="bundle exec rescue `bundle exec which spinach`"
alias rake="bundle exec rake"
alias reset='reset;stty dec new cr0;tset -I -Q'
# gtjan14 alias rm='echo_and_do /bin/rm'
alias rm="rm -v"
alias rspec="bundle exec rspec --color --format documentation"
alias spinach="bundle exec spinach"
alias SU=/usr/local/SU
alias vi_tags='ctags -R --tag-relative=yes -f ~/.vimtags --exclude="*.vim" --exclude=".#?*"'
# if which supports --read-alias (and by inference --read-function), then define a handy alias
if `which --help 2> /dev/null | grep --silent -e "--read-alias"`
then
  alias which='(alias; declare -f) | which --tty-only --read-alias --read-functions --show-tilde --show-dot'
fi
alias whoc='((who; users | wc -w) | pr -l18 -t -2)'
alias x='clear'
alias xrs='xrdb -query'
alias xssh='ssh -X'
#
function xicon()  { echo """]1;$@"; }
function xtitle() { echo """]2;$@         `hostname`"; }
function xboth()  { xicon $@; xtitle $@; }
