# .bash_aliases
# Modification History
# ~~~~~~~~~~~~~~~~~~~~
# Jul-16 glt  Add alias for 'sync' which, unlike other unices, take minutes to run instead of seconds.
# Jan-16 glt	Cleanup unused and os-specific aliases and added shutdown/startup md aliases
# Aug-14 glt  Remove ancient 'print' and other older, unused aliases.
# Jul-14 glt  Add alias for pry-rescue with spinach.  [May not be working]
# Mar-14 glt	Add alias for common Heroku mispelling
#		Change emacs aliases to use Emacs daemon
# Jan-14 glt	Add alias for git to hub; added completion for hub and git
# 	 	Add alias for calling MacOSX Emacs directly from cmd line
# 	 	Add some git aliases
# Dec-13 glt	Adjust emacs definitions for MacOSX
# Nov-13 glt	Add code to enable shims and autocompl for RUBY and
# 	 	completion for homebrew; removed mh directory append
# Dec-11 glt	Add hptemp alias
# Apr-11 glt	Change $* to "$@" so that multi-word args work properly.
# Jan-10 glt	add check for /usr/bin/mh in PATH
# Aug-09 glt	add local dirs to PATH, if needed
# Jul-09 glt	convert to .bash_aliases for Ubuntu
# Mar-01 glt	Add aliases for NetApp
# Jun-00 GLT	Update DISPLAY setting for combined Tru64/Linux use
#		force TERM=xterm-* to be TERM=xterm for Tru64
# Dec-98 GLT	Replace most \!* csh aliases with echo_and_do invocation
#		Comment out those that did not translate well
# Nov-98 GLT	Port from .cshrc

#
# allows args to be displayed prior to execution
# arg1 must be the command name
#
function echo_and_do()
    {
    echo 2>&1 "--> $@" 2> /dev/tty
    "$@"
    }

#
# allows cmd to immediately execute in the background
# arg 1 must be the command name
#
function do_background()
    {
    "$@" &
    }

#
# executes arg1 as a command after executing the remainder
# of the line as a command
# arg 1 must be the post-command in its entirety
# arg 2 must be the command name
#
function do_after()
    {
    local postcmd=$1
    shift

    "$@" ; $postcmd
    }


#++
# add completion extensions
for i in ~/.git-completion.bash ~/.hub.bash_completion.sh
do
  test -f $i && source $i
done

# use --color, when able; also follow symlinks, use human sizes + show file types
lscmd="ls -FshH"
alias ls="$lscmd"
ls --color /tmp > /dev/null 2>&1 &&
  alias ls="$lscmd --color"

#alias ffm='defaults write com.apple.Terminal FocusFollowsMouse -bool '
alias cd='pushd'
alias bk='popd'
# convenience aliases if we are using bundle
test `which bundle 2> /dev/null` && {
  alias be='bundle exec'
  alias cap="be cap"
  alias cucumber="be cucumber"
  alias rake="be rake"
  alias rspec="be rspec --color"
  alias spinach="be spinach"
}
alias cp="cp -v"
alias du='du -h' # human-readable sizes
alias df='df -Ph' # human-readable sizes
alias ecco="wine '/Users/tarsa/.wine/drive_c/Program Files/ECCO/eccoext' 2> /tmp/ecco.wine.errs.txt &"
# on Mac OS X, we prefer to use Emacs in the terminal window
alias emacs='\ec -nw --quiet'
alias xemacs='do_background ~/bin/ec --quiet'
test `which git 2> /dev/null` && {
  test `uname` = Darwin && alias git=hub
  alias gd="git diff"
  alias gs="git status"
}
alias grep='grep -s'  # inhibit "...Is a directory" messages
alias gvim='gvim 2> /dev/null 1>&2'
alias herokup=heroku  # spello preventer
# Mac OS X-only aliases
case `uname` in
  Darwin)
    alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
    alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
    alias sync="echo 'This not the command you are looking for.  Move along.'"

    # in El Capitan, the new lowpri_throttle seems to negatively impact
    # time machine backups.
    alias tm-status='a=`sysctl debug.lowpri_throttle_enabled`; case `echo "$a" | sed "s/^.*: //"` in *0*) echo "TM is fast.";; *) echo "TM is slow" ;; esac'
    alias tm-slow='sudo sysctl -w debug.lowpri_throttle_enabled=1'
    alias tm-fast='sudo sysctl -w debug.lowpri_throttle_enabled=0'
    ;;
esac
alias his='x;history 22'
alias hist="x;history 44 | sed 's/\[[0-9].*[0-9]\] //' | pr -w`tput cols` -2 -l22 -t"
function home()  { cd $1; cd; bk; }
alias iostat='iostat -h' # human-readable sizes
alias ip=aws_asg_to_ip.sh
alias load=uptime
alias mar='sed "s/^/	/" '
# NMH aliases
test `which next 2> /dev/null` && {
	alias n="next"
	alias rs="rmm;next"
	alias rp="rmm;prev"
	alias pack="folder -pack"
	alias pick="do_after 'scan pick' pick -sequence pick"
	alias repl="repl -filter ~/MH-mail/repl.filter -nocc all"
	alias cur="folder | sed 's/+//g;s/\.//g;s/;//g' | awk '{printf "'"+%s %s\n", $1, $9}'"'"
	alias jforw="forw -form joke-components"
}
alias mq='sendmail -bp'
alias mqueue=mq
alias mv='mv -v'
# Ubuntu options
test `uname` = Linux && {
  alias open="exo-open"
  alias pkgupdate="do_background gksudo synaptic"
}
alias rcp="echo_and_do /bin/rcp"
alias reload='xrdb -load ~/.Xdefaults'
test `uname` = Linux &&
  alias ssh="ssh -X" # enable X11 pass through by default
case `uname` in
  Linux) alias rm="rm -v --preserve-root" ;;
  *)     alias rm="rm -v" ;;
esac
alias SU=/usr/local/SU
alias vi_tags='ctags -R --tag-relative=yes -f ~/.vimtags --exclude="*.vim" --exclude=".#?*"'
# if which supports --read-alias (and by inference --read-function), then define a handy alias
if `which --help 2> /dev/null | grep --silent -e "--read-alias"`
then
  alias which='(alias; declare -f) | which --tty-only --read-alias --read-functions --show-tilde --show-dot'
fi
alias whoc='((who; users | wc -w) | pr -l18 -t -2)'
alias x='clear'
alias xrs='xrdb -query'
alias xssh='ssh -X' # enable X11 passthru by default
# icon manipulation.  Works for most/many terminal emulators
function xicon()  { echo """]1;$@"; }
function xtitle() { echo """]2;$@         `hostname`"; }
function xboth()  { xicon $@; xtitle $@; }

# define handy couchdb aliases, if there is a file full of them
test -f ~/.bash_aliases_couchdb && source ~/.bash_aliases_couchdb
