#! /bin/sh
#
# Script to read a list of names and send out appropriate peer-input request
# letters
#
# Modification History
# ~~~~~~~~~~~~~~~~~~~~
# 07	May-2008, Greg Tarsa
#	Updated default for text template.
#
# 06	Apr-2007, Greg Tarsa
#	Fixed mksubjectlist to properly replace the last "," in a list with
#       the word "and."
#	Fixed "send messages" to take up less vertical space.
#	Presumes use of /bin/echo w/ "\c" to inhibit trailing CRLF
# 
# 05	Mar-2005, Greg Tarsa
#	Made the template file a variable; set to grab the group template
# 
# 04	May-2004, Greg Tarsa
#	Add code to key in on "but also" in addition to other strings.
#
# 03	May-2003, Greg Tarsa
#	Changed to take all input in a single tab-delimited line.
#	Added -send option.
#
# 02	Jun-2002, Greg Tarsa
#	Updated to make into peer-input generator.
#
# 01	Jul-1999, Greg Tarsa
#	Wrote original code.
#

Usage='
    USAGE: peer-input [-option] input_file

    Generate e-mail messages requesting peer-input from the folks in
    the input_file.

    Default is to print the e-mail to stdout.

    Options include:
	-s[end]	  	actually send the e-mail messages.
	-d[ebug]	enable debug messages

    ----
    input file consists of data sets of a single line w/ fields
    delimited by tabs:

    <desc>\t<last>\t<first>\t<email>\t<list>

       <desc>	(unused) must be non-null
       <last>	(unused) last name of recipient
       <first>	first name of recipient
       <email>	email of recipient (will have @netapp.com appended)
       <list>	list of people you want input on

    e-mail will be sent to each address in the list.

    The list of people you want input on should be comma delimited and
    fit in a sentence like: "I would like input on <list>."

    The format of the file lends itself to an excel spreadsheet
    written out as a tab-delimited file.
'
nl='
'

myemail="tarsa@netapp.com"
send="no"
input_file=""
debug="no"
template_file="$HOME/templates/peer-input-request-fy08.txt"

# mksubjectlist
# Change the last comma of a comma list of 3 or more names into an "and"
# Return other lists w/o change.
#
# this returns a string, so it should be called in backquotes
mksubjectlist () {
     subjectlist=

     #echo 1>&2 "arglist='$*'"

     subjectlist=`echo "$*" | sed 's/\(.*\),/\1 and/'`
     #echo 1>&2 "adjusted subjectlist ='$subjectlist'"

echo "$subjectlist"
}

while :
do
    # No more arguments?  All Done.
    case $# in
       0) break ;;
    esac

    # process the switches
    case $1 in
       # set the "really send" flag
       -send|-s*)
            send="yes"
	    ;;
	    
       # set the debug flag
       -debug|-d*)
            debug="yes"
	    ;;
	    
       -*) echo 1>&2 "?Invalid switch: $1"; errflg=yes ;;
        *) input_file="$1"
	   ;;
    esac
    shift
done

case $input_file in
    "") echo 1>&2 "?No input file specified"; errflg=yes ;;
esac

case $template_file in
    "") echo 1>&2 "?No template file specified"; errflg=yes ;;
esac

case $errflg in
   yes) echo 1>&2 "$Usage$nl"; exit 0 ;;
esac

if test ! -s $input_file
then
    echo 1>&2 "?data file is empty."
    errflg=yes
fi

if test ! -s $template_file
then
    echo 1>&2 "?template file, $template_file, is empty."
    errflg=yes
fi

case $errflg in
   yes) echo 1>&2 "$Usage$nl"; exit 0 ;;
esac

case $send in
    yes) echo "Mail will be sent when you hit Enter: "; read dummy ;;
esac

# remove quote marks from the file and pipe to the big filter
sed '	s/"//g
 	s/\.//g' $input_file |
while : 
do
     # read the data line, break it into arguments
     read data || break

     IFS="	"
     set $data

     desc=$1
     last=$2
     first=$3
     email="$4@netapp.com"
     list=`echo "$5" | sed 's///'`

     # sanity check the arguments
     case $first in "") echo 1>&2 "?first name is null: '$*'"; errflg=1;; esac
     case $email in "") echo 1>&2 "?email addr is null: '$*'"; errflg=1;; esac
     case $list in "") echo 1>&2 "?list is null: '$*'"; errflg=1;; esac
     case $errflg in
         "") ;;
	 *) break ;;
     esac

     subjectlist="`mksubjectlist $list`"
     case $debug in
        yes)
	    echo "desc= $desc"
	    echo "first last= $first $last"
	    echo "email= $email"
	    echo "list= $list"
	    echo "cmd: Mail -b $myemail -s " '"Focal Review Input Requested for' $subjectlist'"' $email
	    ;;
	*)
	    # in real production, skip the header row.
	    case $first$last$desc in
	        firstlastdesc) continue ;;
	    esac
	    echo Input for: $subjectlist
	    echo "${email}: \c"
	    ;;
     esac

     sed "s=+emp-list+=$subjectlist=
	  s/+Firstname+/$first/" $template_file |
	  fmt -w 63 |
	  sed 's/^\.//' |
	  case $send in
	      yes) Mail -b $myemail -s "Focal Input Requested for $subjectlist" $email ;;
	      *) case $debug in yes) ;; *) more;; esac ;;
	  esac

     case $debug in
        yes) echo "------" ;;
	*)   case $send in
	         yes) echo "Sent." ;;
		 no)  echo "Not Sent." ;;
	     esac
	     ;;
     esac
     echo
done
