#!/bin/bash
#
# Quick script to unpack Verizon log tarfiles and summarize pertinent info from ntap_sol_info files
#
# Usage = "vzn_analy file1 [file2...]"
#
# Assumes that "file" is a tar file
#
# Modification History
# ~~~~~~~~~~~~~~~~~~~~
# 01	Jun-2006, Greg Tarsa
#	Wrote original code

nl="
"
curdir=`pwd`
while :
do

    case $# in
       0) echo "done"; break ;;
    esac

    rawname=$1; shift
    rawname=`echo "$rawname" | sed 's/\.tar//'`
    #rawname="v8ttqpa4_1524855"
    host="`echo $rawname | sed 's/_.*//'`"
    analy_file=../summary-$rawname"".txt

    cd $curdir

    test -r $rawname"".tar ||
	{
	echo $rawname"".tar not found.  exiting
	exit 1
	}


    test -d $rawname &&
	{
	echo directory for $rawname already exists.  skipping.
	continue
	}

    mkdir $rawname ||
        {
        echo mkdir $rawname failed. exiting
        exit 1
        }

    
    cd $rawname ||
        {
	echo "Unable to chdir to $rawname.  exiting"
	exit 1
	}

    echo processing $rawname...

    {
    tar xf ../$rawname"".tar
    uncompress *.Z

    tar xf ntap_sol_info.tar

    cd ntap_sol_info

    # write output header
    echo "$rawname"": Summary of Pertinent settings${nl}"

    # dump nodev & lnkdown timeout values
    echo "lpcf.conf settings of interest:"
    egrep -i "nodev-tmo|linkdown-tmo" lpfc.conf

    # dump HBA info for each HBA
    echo "${nl}HBA info:"
    egrep "^lpfc|^WWNN|^model|^driver version|^firmware version" adapters |
	sed '/^lpfc/{x;p;x;}'

    # dump Solaris version
    echo "${nl}"
    grep -i solaris etc_release | sed 's/^  *//' 
    cat uname_a

    # dump Veritas versions
    echo "${nl}Veritas versions:"
    grep -i vx modinfo | sed 's/^...........................//' 

    # dump ASL version
    echo "${NL}" 
    grep -i "array support" packages | head -1 | sed 's/^  *//'
    awk 'BEGIN {print_version=0}
	/PKGINST.*NTAPasl/{print_version=1; print $0}
	/VERSION:/{if (print_version==1) {print $0; print_version=0} }' packages


    # dump /etc/system params of interest
    echo "${nl}/etc/system parameters"
    grep "^set.*sd:" system

    } > $analy_file
done 
