#!/bin/sh
#
# arp2ethers - converts the output of an arp -a command into a file
# suitable for appending to an existing Etherboy ethers file.
#
tmpfile1=/tmp/arpether-$$a
tmpfile2=/tmp/arpether-$$b

# cleanup on exit or error
trap 0 'rm -f *-$$.'

cut -d' ' -f 1,4 > $tmpfile1
cut -d' ' -f 1 $tmpfile1 > $tmpfile2
cut -d' ' -f 4 |
	paste - $tmpfile1 |
	grep -v incomplete |
	sed 's/^[ 	]*//g;s/\.zko\.dec\.com//'
