#!/bin/bash -i
# needs to be an interactive shell to get aliases

for cmd
do
  found=""

  OFS="$IFS"
  IFS=":"
  for i in $PATH
  do
    if [ -f $i/$cmd ]
    then
      echo "$cmd found in $i"
      found="y"
    fi
  done
  IFS="$OFS"

  alias_item=`alias | grep -s "alias\s$cmd="`
  case $alias_item in
    "") ;; # not found
    *) echo "$cmd found as: $alias_item"
       found="y"
       ;;
  esac 

  case $found in
    "") echo "$cmd not found in path\n";;
  esac
  echo " "
done

exit
