#!/bin/bash -i
# needs to be an interactive shell to get aliases

for cmd
do
  found=""

  # Search the PATH
  OFS="$IFS"
  IFS=":"
  for i in $PATH
  do
    if [ -f $i/$cmd ]
    then
      echo "$cmd found in $i"
      found="y"
    fi
  done
  IFS="$OFS"

  # Search the aliases
  alias_item=`alias | grep -s "alias\s$cmd="`
  case $alias_item in
    "") ;; # not found
    *) echo "$cmd found as: $alias_item"
       found="y"
       ;;
  esac

  # Search the functions
  . ~/.bash_aliases
  function_item=`declare -f "$cmd"`
  case $function_item in
    "") ;; # not found
    *) echo "$cmd found as: $function_item"
       found=y
       ;;
   esac

  case $found in
    "") echo "$cmd not found in path, aliases, or functions";;
  esac
  echo " "
done

exit
