#!/bin/bash
#
# Quick script to unpack Verizon log tarfiles and summarize pertinent info from ntap_sol_info files
#
USAGE='Usage: sol-info-analy -o[utput] title-string info-dir

title-string is the string used to name the output file
             ("title-string".txt) and will be in the distillation
              output file as a title.

info-dir     is the name of the directory containing the unpacked
             solaris_info tarfile output.
'
#
# Modification History
# ~~~~~~~~~~~~~~~~~~~~
# 02	Oct-2006, Greg Tarsa
#	Revised to work with general ntap_sol_info directories.
#
# 01	Jun-2006, Greg Tarsa
#	Wrote original code to analyze Verizon info dump tar files.

nl="
"
curdir=`pwd`

titlestring="default"
infodir=""
errflag=""

# process switches
while :
do
    # No more arguments?  All Done.
    case $# in
       0) break ;;
    esac

    # process the switches
    case $1 in

       # get the title-string
       -title|-t*) titlestring="" ;;

       # not a recognized switch string...
       -*) echo 1>&2 "?Invalid switch: $1"; errflag=yes ;;
       
       # not a switch? Then move on...
       *) break ;;
    esac

    shift # get next word to process
done

# Get the infodir, there should be only 1 arg
case $# in
   1) infodir=$1
      errflag=""
      ;;
   *) errflag="yes"
      echo 1>&2 "Only 1 argument allowed; $# found."
      ;;
esac

case $errflag in
   yes) echo 1>&2 "$USAGE"; exit 1 ;;
esac

host="$titlestring"
analy_file=$curdir/summary-$titlestring"".txt

#verify the validity of the target directory
cd $infodir ||
    {
    echo "Unable to chdir to $infodir.  exiting"
    exit 1
    }

echo processing $infodir...

# put the following in a block so we can re-direct output in only one place
{
    # write output header
    echo "$titlestring"": Summary of Pertinent settings${nl}"

    # dump nodev & lnkdown timeout values
    echo "lpcf.conf settings of interest:"
    egrep -i "nodev-tmo|linkdown-tmo" lpfc.conf

    # dump HBA info for each HBA
    echo "${nl}HBA info:"
    egrep "^lpfc|^WWNN|^model|^driver version|^firmware version" adapters |
	sed '/^lpfc/{x;p;x;}'

    # dump Solaris version
    echo "${nl}"
    grep -i solaris etc_release | sed 's/^  *//' 
    cat uname_a

    # dump Veritas versions
    echo "${nl}Veritas versions:"
    grep -i vx modinfo | sed 's/^...........................//' 

    # dump ASL version
    echo "${NL}" 
    grep -i "array support" packages | head -1 | sed 's/^  *//'
    awk 'BEGIN {print_version=0}
	/PKGINST.*NTAPasl/{print_version=1; print $0}
	/VERSION:/{if (print_version==1) {print $0; print_version=0} }' packages


    # dump /etc/system params of interest
    echo "${nl}/etc/system parameters"
    grep "^set.*sd:" system

} > $analy_file

echo output is in $analy_file
exit

