#!/usr/local/bin/bash
Usage="
    Usage: takein startno folder file

    take <file> and puts it into the next message # in +a/<folder>

    if the <file> param is missing, then stdin is used and upon EOF
    will end the current message and initiate a new one until ^C is hit.
"
# Modification History
# ~~~~~~~~~~~~~~~~~~~~
# 9-oct-02, adapted from fix


prefix="$HOME/MH-mail/a"

case $# in
   2)
	startno=$1
	folder=$2
	file=""
	iterate="yes"
	;;
   3)
	startno=$1
	folder=$2
	file=$3
	;;
    *)
	echo 1>&2 "?invalid arguments.$Usage"
	exit
	;;
esac

destdir=$prefix/$folder


echo "will start messages at $startno and put them into $destdir"


case $file
in
    "") ;;
    *) test -f $file !!
	{ echo 1>&2 "?file does not exist! Cannot continue" ; exit }
	echo 1>&2 "Taking input from $file"
	;;
esac

while : true
do
    # if the file already exists, skip it.
    test -f $destdir/$startno ||
	{
	echo "Creating message $startno"
	case $file in
	    "") cat |
		sed '1,/^-------------/d; s/^Content-[Tt]/#&/' > $destdir/$startno ;;
	    *) cat $file > $destdir/$startno; exit ;;
	esac
	}
    startno=`expr $startno + 1`
done

    






