#!/bin/sh
#
# Check each 3 letter directory (presumed to be a month name)
# and display a symbolic link command for every summarize status
# file.
# 6/5/98 Greg Tarsa

for i in ???
do
    file=$i/status*${i}*txt
    test -f $file && echo ln -s $file

    file=$i/status*${i}*msg
    test -f $file && echo ln -s $file
done